version: '3.3'
services:
  nginx:
    image: nginx:1.17.5-alpine
    volumes:
      - ./:/var/www
      - ./etc/docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Europe/Moscow
    working_dir: /var/www/
    ports:
      - "8012:80"
    networks:
      default:
        aliases:
          - weldbook_nginx
  php:
    image: serieznyi/test-weldbook-php:1.0.0
    volumes:
      - ./:/var/www
    environment:
      - TZ=Europe/Moscow
    working_dir: /var/www/

  mysql:
    image: mysql:8.0.18
    ports:
      - "8006:3306"
    volumes:
      - ./etc/docker/services/mysql/conf.d:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
