#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use Symfony\Component\Dotenv\Dotenv;
use yii\console\Application;
use Zend\ConfigAggregator\ConfigAggregator;
use Zend\ConfigAggregator\PhpFileProvider;

require(__DIR__ . '/vendor/autoload.php');

$dotEnv = new Dotenv();
$dotEnv->load(__DIR__ . '/.env');

\defined('YII_DEBUG') or \define('YII_DEBUG', \Helpers\getenv('YII_DEBUG'));
\defined('YII_ENV') or \define('YII_ENV', \Helpers\getenv('YII_ENV'));
\defined('YII_ENV_LOCAL') or \define('YII_ENV_LOCAL', YII_ENV === 'Local');
\defined('YII_ENV_DEV') or \define('YII_ENV_DEV', YII_ENV === 'Development');
\defined('YII_ENV_RLS') or \define('YII_ENV_RLS', YII_ENV === 'Release');

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

require(__DIR__ . '/config/bootstrap.php');

$aggregator = new ConfigAggregator([
    new PhpFileProvider(__DIR__ . '/config/*.{main,local}.php'),
    new PhpFileProvider(__DIR__ . '/config/console/*.{main,local}.php'),
]);

$application = new Application($aggregator->getMergedConfig());
$exitCode = $application->run();
exit($exitCode);
